name: guns.lol r Monitor

on:
  workflow_dispatch:          # Allows manual trigger
  schedule:
    - cron: "*/2 * * * *"    # Every 10 minutes (adjust as needed)

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    env:
      CHECK_INTERVAL: 10       # Check every 45 seconds (recommended)
      WEBHOOK_AVAILABLE: ${{ secrets.WEBHOOK_AVAILABLE }}
      WEBHOOK_TAKEN: ${{ secrets.WEBHOOK_TAKEN }}
      WEBHOOK_BANNED: ${{ secrets.WEBHOOK_BANNED }}
      WEBHOOK_RATE: ${{ secrets.WEBHOOK_RATE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright Chromium
        run: |
          playwright install chromium --with-deps

      - name: Run r Monitor
        run: |
          python main.py
